version: '3.1'

services:
  dc:
    build: streamsets
    ports:
      - "18630:18630"
    restart: on-failure
    volumes:
      - ./volumes/sdc-data:/data

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: adtech
    volumes:
      - "./volumes/mongo-data:/data/db"
      - "./volumes/mongo-imports:/home"

  agent:
    build: agent
    restart: always
    environment:
      STREAMSETS_USERNAME: 'admin'
      STREAMSETS_PASSWORD: 'admin'
      STREAMSETS_URL: 'http://dc:18630'
      LOG_FILE_PATH: '/var/log/agent.log'
    stdin_open: true
    tty: true
    depends_on:
      - dc
      - mongo
