version: '3.1'

services:
  dc:
    build: streamsets
    ports:
      - "18630:18630"
    restart: on-failure
    volumes:
      - sdc-data:/data
    extra_hosts:
      - "daria-test2:10.0.0.28"

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - /data/db
      - ./test-datasets:/home
      - ./volumes/mongo-initdb:/docker-entrypoint-initdb.d

  agent:
    build: agent
    restart: always
    environment:
      STREAMSETS_USERNAME: 'admin'
      STREAMSETS_PASSWORD: 'admin'
      STREAMSETS_URL: 'http://dc:18630'
      LOG_FILE_PATH: '/var/log/agent.log'
      ANODOT_API_URL: 'http://anodotd:8080'
      SDC_DATA_PATH: '/sdc-data'
    stdin_open: true
    tty: true
    depends_on:
      - dc
      - mongo
    volumes:
      - sdc-data:/sdc-data
      - agent-data:/usr/src/app/data

volumes:
  sdc-data:
  agent-data:
