services:
  dc:
    platform: linux/amd64
    build:
      context: ../../containers/streamsets
    ports:
      - "18630:18630"
    restart: on-failure
    volumes:
      - ./sdc-data:/data
      - ./sdc-conf:/etc/sdc_conf

  agent:
    platform: linux/amd64
    build:
      context: ..
      dockerfile: Dockerfile.actian.local
    restart: always
    environment:
      STREAMSETS_USERNAME: 'admin'
      STREAMSETS_PASSWORD: 'admin'
      STREAMSETS_URL: 'http://dc:18630'
      ENV_PROD: 'false'
      AGENT_DB_HOST: 'db'
      AGENT_DB_USER: 'agent'
      AGENT_DB_PASSWORD: 'agent'
      GIT_SHA1: 'local'
      AGENT_URL: 'http://anodot-agent'
      PGPASSWORD: 'agent'
      TLS_VERSION: '1.1'
      LOG_LEVEL: 'DEBUG'
    depends_on:
      - dc
      - db
    volumes:
      - ../backup-data:/usr/src/app/backup-data
      - ../output:/output
      - ../:/usr/src/app
    ports:
      - "80:80"

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: agent
      POSTGRES_PASSWORD: agent
      POSTGRES_DB: agent
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data


volumes:
  agent-data:
  db-data:
