services:
  dc:
    platform: linux/amd64
    image: anodot/streamsets:latest
    ports:
      - "18630:18630"
    restart: on-failure
    environment:
      SDC_CONF_PRODUCTION_MAXBATCHSIZE: "50"
      SDC_JAVA_OPTS: "-Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8 -Xmx4096m -Xms4096m -server"
      SDC_CONF_RUNNER_THREAD_POOL_SIZE: "2000"
    volumes:
      - ./sdc-data:/data
      - ./sdc-conf:/etc/sdc_conf

  agent:
    platform: linux/amd64
    build:
      context: ..
      dockerfile: Dockerfile.actian
    restart: always
    environment:
      AGENT_DB_HOST: 'db'
      AGENT_DB_USER: 'agent'
      AGENT_DB_PASSWORD: 'agent'
    depends_on:
      - dc
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: agent
      POSTGRES_PASSWORD: agent
      POSTGRES_DB: agent
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data


volumes:
  agent-data:
  db-data:
