apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: {{ include "agent.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "agent.name" . }}
    helm.sh/chart: {{ include "agent.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "agent.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "agent.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: streamsets
          image: "{{ .Values.streamsets.repository }}:{{ .Values.streamsets.tag }}"
          imagePullPolicy: {{ .Values.streamsets.pullPolicy }}
          {{- if .Values.streamsets.env }}
          env:
          {{- range $name, $value := .Values.streamsets.env }}
            - name: "{{ $name }}"
              value: "{{ $value }}"
          {{- end }}
          {{- end }}
          volumeMounts:
            - mountPath: /data
              name: agent-data
          ports:
            - name: http
              containerPort: 18630
              protocol: TCP
          livenessProbe:
              httpGet:
                path: /
                port: 18630
          readinessProbe:
              httpGet:
                path: /
                port: 18630
          resources:
{{ toYaml .Values.streamsets.resources | indent 12 }}
        - name: agent
          image: "{{ .Values.agent.repository }}:{{ .Values.agent.tag }}"
          imagePullPolicy: {{ .Values.agent.pullPolicy }}
          volumeMounts:
            - mountPath: /sdc-data
              name: agent-data
            - mountPath: /usr/src/app/data
              name: agent-data
              subPath: data
          env:
            - name: STREAMSETS_URL
              value: "{{ .Values.streamsetsurl }}"
            - name: ANODOT_API_URL
              value: "{{ .Values.anodotapiurl }}"
          command: ['sh', '-c', 'while true; do echo "The app is running with streamset_url: $STREAMSETS_URL and anodot_api as: $ANODOT_API_URL"; sleep 600; done']
          resources:
{{- toYaml .Values.agent.resources | indent 12 }}
{{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: agent-data
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
        {{- if .Values.persistence.storageClass }}
        {{- if (eq "-" .Values.persistence.storageClass) }}
        storageClassName: ""
        {{- else }}
        storageClassName: "{{ .Values.persistence.storageClass }}"
        {{- end }}
        {{- end }}
{{- else }}
      volumes:
        - emptyDir: {}
          name: agent-data
{{- end }}