version: '3.1'

services:
  dc:
    image: anodot/streamsets:latest
    restart: on-failure
    container_name: anodot-sdc
    environment:
      SDC_JAVA_OPTS: "-Xmx1024m -Xms1024m -server"
      SDC_CONF_RUNNER_THREAD_POOL_SIZE: "200"
    volumes:
      - sdc-data:/data

  agent:
    image: anodot/daria:latest
    container_name: anodot-agent
    hostname: agent
    restart: always
    stdin_open: true
    tty: true
    depends_on:
      - dc
#    ports:
#    - 8080:80

    volumes:
      - sdc-data:/sdc-data
      - agent-data:/usr/src/app/data

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: agent
      POSTGRES_PASSWORD: agent
      POSTGRES_DB: agent
    volumes:
      - /var/lib/postgresql/data
      - ./init.db:/docker-entrypoint-initdb.d

volumes:
  sdc-data:
  agent-data:
