version: '3.1'

services:
  dc:
    image: anodot/streamsets:latest
    restart: on-failure
    container_name: anodot-sdc
    environment:
      SDC_JAVA_OPTS: "-Xmx8192m -Xms8192m -server"
      SDC_CONF_RUNNER_THREAD_POOL_SIZE: "200"
    volumes:
      - sdc-data:/data
    ulimits:
      nofile:
        soft: 32768
        hard: 32768
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  agent:
    image: anodot/daria:latest
    container_name: anodot-agent
    hostname: agent
    restart: always
    stdin_open: true
    tty: true
    depends_on:
      - dc
      - db
    environment:
      AGENT_DB_HOST: 'db'
      AGENT_DB_USER: 'agent'
      AGENT_DB_PASSWORD: 'agent'
      LISTEN_PORT: 8080
    ports:
      - 8080:8080
    volumes:
      - ./backup-data:/usr/src/app/backup-data
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: agent
      POSTGRES_PASSWORD: agent
      POSTGRES_DB: agent
    volumes:
      - agent-data:/var/lib/postgresql/data
    logging:
      options:
        max-size: "10m"
        max-file: "10"

volumes:
  sdc-data:
  agent-data:
