FROM tiangolo/uwsgi-nginx-flask:python3.7

WORKDIR /usr/src/app

COPY . .
ADD .bashrc /root/.bashrc

VOLUME /usr/src/app/data
RUN apt update && apt install -y vim nano netcat curl nano

ENV DATA_DIR="/data" STREAMSETS_USERNAME="admin" STREAMSETS_PASSWORD="admin" STREAMSETS_URL="http://localhost:18630" \
    LOG_FILE_PATH="/var/log/agent.log" ANODOT_API_URL="http://api.anodot.com" SDC_DATA_PATH="/sdc-data" ENV_PROD='true' \
    GIT_SHA1=local-build VALIDATION_ENABLED="true"

RUN pip install --upgrade pip && pip install -r requirements.txt && python setup.py develop
