FROM tiangolo/uwsgi-nginx-flask:python3.10

#defined in jenklins build, so for any local build it should be explicitly set as following:
#docker build --build-arg GIT_SHA1=$(git describe --tags --dirty --always)
ARG GIT_SHA1=local-build

WORKDIR /usr/src/app

COPY . .
COPY .bashrc /root/.bashr
COPY ./custom_entrypoint.sh /
COPY supervisord.conf /etc/supervisor/supervisord.conf
COPY nginx.conf /etc/nginx/nginx.conf
COPY uwsgi-nginx-entrypoint.sh /uwsgi-nginx-entrypoint.sh
COPY uwsgi.ini /etc/uwsgi/uwsgi.ini

RUN chmod +x /custom_entrypoint.sh /uwsgi-nginx-entrypoint.sh

ENV SDC_CONF_PARSER_LIMIT="20048576" STREAMSETS_USERNAME="admin" STREAMSETS_PASSWORD="admin" \
    STREAMSETS_URL="http://localhost:18630" prometheus_multiproc_dir="/opt/metrics"

# if you change LOG_FILE_PATH you also need to change it in .github/test.yml in Show logs section
ENV LOG_FILE_PATH="/var/log/agent/agent.log" ANODOT_API_URL="https://api.anodot.com" ENV_PROD='true' VALIDATION_ENABLED="true"

RUN ./install_requirements.sh
RUN python setup.py install && echo ". /usr/src/app/agent-complete.sh" >> /root/.bashrc

# actian dependencies
RUN apt-get update && apt-get install sudo
COPY ./actian_config/actian-client /tmp/actian-client
RUN /tmp/actian-client/client_install.sh -express
COPY ./actian_config/odbcinst.ini /etc/odbcinst.ini
ENV II_ODBC_WCHAR_SIZE=2 II_SYSTEM="/opt/Actian/Actian_Client" \
    LD_LIBRARY_PATH=/lib:/usr/lib:/opt/Actian/Actian_Client/ingres/lib:/opt/Actian/Actian_Client/ingres/lib/lp32

RUN groupadd -g 10001 agent && useradd -r -u 10001 -g agent agent
RUN mkdir /var/log/agent /opt/metrics && chown -R agent:agent /var/log/agent /etc/nginx/conf.d /etc/supervisor/conf.d \
/var/log/supervisor /var/cache/nginx /var/cache/nginx /usr/src/app /opt/metrics
USER agent

ENTRYPOINT ["/custom_entrypoint.sh"]
CMD ["/start.sh"]
