name: Release

on:
  release:
    types:
      - created

jobs:
  start-runner:
    name: Start self-hosted EC2 runner
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-2'
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.TOKEN_GH }}
          ec2-image-id: ami-0a37bd595acad3c01
          ec2-instance-type: t3.2xlarge
          subnet-id: subnet-0e7811da2dc0b7fc7
          security-group-id: sg-0db7cdfa3dd74fbce
  build:
    runs-on: ${{ needs.start-runner.outputs.label }}
    needs: start-runner
    steps:
    - uses: actions/checkout@v1

    - name: Increase vm memory
      run: sudo sysctl -w vm.max_map_count=262144

    - name: Build
      run: make build-all

    - name: Check version
      run: VERSION=${GITHUB_REF/refs\/tags\//} && ver=$(docker exec -i anodot-agent agent -v | grep version | cut -d' ' -f4) && if [ ${ver} != $VERSION ]; then exit 1; fi

    - name: Test
      run: make test-all

    - if: ${{ !contains(github.ref, 'beta') }}
      name: Tag latest
      run: docker image tag daria_agent:latest anodot/daria:latest && docker image tag daria_dc:latest anodot/streamsets:latest

    - name: Tag version
      run: VERSION=${GITHUB_REF/refs\/tags\//} && docker image tag daria_agent:latest anodot/daria:$VERSION && docker image tag daria_dc:latest anodot/streamsets:$VERSION

    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - if: ${{ !contains(github.ref, 'beta') }}
      name: Push latest
      run: docker push anodot/daria && docker push anodot/streamsets

    - name: Push images
      run: VERSION=${GITHUB_REF/refs\/tags\//} && docker push anodot/daria:$VERSION && docker push anodot/streamsets:$VERSION
  stop-runner:
    name: Stop self-hosted EC2 runner
    needs:
      - start-runner
      - build 
    runs-on: ubuntu-latest
    if: ${{ always() }} 
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-2'
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.TOKEN_GH }}
          label: ${{ needs.start-runner.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner.outputs.ec2-instance-id }}