name: Release

on:
  release:
    types:
      - created

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: docker-compose build --build-arg GIT_SHA1=$(git describe --dirty --always)

    - name: Prepare env
      run: docker-compose up -d && ./setup_tests.sh
    
    - name: Check version
      env:
        GIT_REF: ${{ github.ref }}
      run: VERSION=${GIT_REF/refs\/tags\//} && ver=$(docker exec -i anodot-agent agent -v | grep version) && if [ ${ver#*:} != $VERSION ]; then exit 1; fi 

    - name: Test
      run: docker exec -i anodot-agent pytest -x 
      
    - name: Tag latest
      run: docker image tag daria_agent:latest anodot/daria:latest && docker image tag daria_dc:latest anodot/streamsets:latest
      
    - name: Tag version
      run: docker image tag daria_agent:latest anodot/daria:$VERSION && docker image tag daria_dc:latest anodot/streamsets:$VERSION
      
    - name: Push images
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} && docker push anodot/daria && docker push anodot/streamsets
