name: Release

on:
  release:
    types:
      - created

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Increase vm memory
      run: sudo sysctl -w vm.max_map_count=262144

    - name: Build
      run: make build-all

    - name: Check version
      run: VERSION=${GITHUB_REF/refs\/tags\//} && ver=$(docker exec -i anodot-agent agent -v | grep version | cut -d' ' -f4) && if [ ${ver} != $VERSION ]; then exit 1; fi

    - name: Test
      run: make test-all

    - if: ${{ !contains(github.ref, 'beta') }}
      name: Tag latest
      run: docker image tag daria_agent:latest anodot/daria:latest && docker image tag daria_dc:latest anodot/streamsets:latest

    - name: Tag version
      run: VERSION=${GITHUB_REF/refs\/tags\//} && docker image tag daria_agent:latest anodot/daria:$VERSION && docker image tag daria_dc:latest anodot/streamsets:$VERSION

    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - if: ${{ !contains(github.ref, 'beta') }}
      name: Push latest
      run: docker push anodot/daria && docker push anodot/streamsets

    - name: Push images
      run: VERSION=${GITHUB_REF/refs\/tags\//} && docker push anodot/daria:$VERSION && docker push anodot/streamsets:$VERSION
