name: Release

on:
  release:
    types:
      - created

jobs:
  test-general:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1

      - name: Increase vm memory
        run: sudo sysctl -w vm.max_map_count=262144

      - name: Build
        run: make build-all

      - name: Test
        run: make test-general

      - name: Show logs
        if: ${{ failure() }}
        run: make show-all-logs

  test-pipelines-1:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1

      - name: Increase vm memory
        run: sudo sysctl -w vm.max_map_count=262144

      - name: Build
        run: make build-all

      - name: Test
        run: make test-pipelines-1

      - name: Show logs
        if: ${{ failure() }}
        run: make show-all-logs

  test-pipelines-2:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1

      - name: Increase vm memory
        run: sudo sysctl -w vm.max_map_count=262144

      - name: Build
        run: make build-all

      - name: Test
        run: make test-pipelines-2

      - name: Show logs
        if: ${{ failure() }}
        run: make show-all-logs
  release:
    runs-on: ubuntu-20.04
    needs: [test-general, test-pipelines-1, test-pipelines-2]
    steps:
    - uses: actions/checkout@v1

    - name: Increase vm memory
      run: sudo sysctl -w vm.max_map_count=262144

    - name: Check version
      run: VERSION=${GITHUB_REF/refs\/tags\//} && ver=$(docker exec -i anodot-agent agent -v | grep version | cut -d' ' -f4) && if [ ${ver} != $VERSION ]; then exit 1; fi

    - if: ${{ !contains(github.ref, 'beta') && !contains(github.ref, 'release') }}
      name: Tag latest
      run: docker image tag daria_agent:latest anodot/daria:latest && docker image tag daria_dc:latest anodot/streamsets:latest

    - name: Tag version
      run: VERSION=${GITHUB_REF/refs\/tags\//} && docker image tag daria_agent:latest anodot/daria:$VERSION && docker image tag daria_dc:latest anodot/streamsets:$VERSION

    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - if: ${{ !contains(github.ref, 'beta') }}
      name: Push latest
      run: docker push anodot/daria && docker push anodot/streamsets

    - name: Push images
      run: VERSION=${GITHUB_REF/refs\/tags\//} && docker push anodot/daria:$VERSION && docker push anodot/streamsets:$VERSION
