name: Run tests

on:
  push:
    branches:
    - master

  pull_request:
    branches:
    - master
    - 'release*'

jobs:
  test-general:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1

      - name: Increase vm memory
        run: sudo sysctl -w vm.max_map_count=262144

      - name: Build
        run: make build-all

      - name: Test
        run: make test-general

      - name: Show logs
        if: ${{ failure() }}
        run: make show-all-logs

  test-pipelines-1:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1

      - name: Increase vm memory
        run: sudo sysctl -w vm.max_map_count=262144

      - name: Build
        run: make build-all

      - name: Test
        run: make test-pipelines-1

      - name: Show logs
        if: ${{ failure() }}
        run: make show-all-logs

  test-pipelines-2:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1

      - name: Increase vm memory
        run: sudo sysctl -w vm.max_map_count=262144

      - name: Build
        run: make build-all

      - name: Test
        run: make test-pipelines-2

      - name: Show logs
        if: ${{ failure() }}
        run: make show-all-logs
