name: Run tests

on:
  push:
    branches:
    - master
      
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1

      - name: Get streamsets stages
        run: curl -L https://github.com/anodot/anodot-sdc-stage/releases/download/v1.0/anodot-1.0.tar.gz -o sdc.tar.gz && tar xvfz sdc.tar.gz -C streamsets/lib

      - name: Build
        run: docker-compose up -d --build
      
      - name: Prepare env
        run: sleep 10 && ./setup_tests.sh
        
      - name: Test
        run: docker exec -i anodot-agent pytest -x 
