name: Run tests

on:
  push:
    branches:
    - self-hosted-runner

  pull_request:
    branches:
    - self-hosted-runner

jobs:
  start-runner:
    name: Start self-hosted EC2 runner
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-2'
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.TOKEN_GH }}
          ec2-image-id: ami-0e883b3d05790f9fd
          ec2-instance-type: t3.large
          subnet-id: subnet-0e7811da2dc0b7fc7
          security-group-id: sg-0db7cdfa3dd74fbce
  test:
    runs-on: ${{ needs.start-runner.outputs.label }}
    needs: start-runner
    steps:
      - uses: actions/checkout@v1

      - name: Increase vm memory
        run: sudo sysctl -w vm.max_map_count=262144

      - name: Build
        run: make build-all

      - name: Test
        run: make test-all

      - name: Show logs
        if: ${{ failure() }}
        run: >
          docker logs anodot-agent;
          echo "DC logs "; docker logs dc;
          echo "DC 2 logs"; docker logs dc2;
          echo "Kafka logs"; docker logs agent-kafka;
          echo "Dummy logs"; docker logs dummy_destination;
          echo "Agent logs"; docker exec -i anodot-agent cat /var/log/agent/agent.log;
          echo "VictoriaMetrics logs"; docker logs victoriametrics;
  stop-runner:
    name: Stop self-hosted EC2 runner
    needs:
      - start-runner
      - test 
    runs-on: ubuntu-latest
    if: ${{ always() }} 
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-2'
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.TOKEN_GH }}
          label: ${{ needs.start-runner.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner.outputs.ec2-instance-id }}
