name: Run tests

on:
  push:
    branches:
    - master
      
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: docker-compose up -d --build
      
      - name: Prepare env
        run: ./setup_tests.sh
        
      - name: Test
        run: sleep 10 && docker exec -i anodot-agent pytest -x 
