name: Run tests

on:
  push:
    branches:
    - master
      
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1

      - name: Increase vm memory
        run: sudo sysctl -w vm.max_map_count=262144

      - name: Build
        run: make build-all

      - name: Test
        run: make test-all

      - name: Show logs
        if: ${{ failure() }}
        run: docker logs anodot-agent ; echo "\nDC logs\n" ; docker logs dc ; echo "\nDC 2 logs\n" ; docker logs dc2 ; echo "\nKafka logs\n" ; docker logs agent-kafka ; echo "\nDummy logs\n" ; docker logs dummy_destination
