name: Run tests

on:
  push:
    branches:
    - master
      
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1

      - name: Increase vm memory
        run: sudo sysctl -w vm.max_map_count=262144

      - name: Build
        run: make build-all

      - name: Test
        run: make test-all

      - name: Show logs
        if: ${{ failure() }}
        run: >
          docker logs anodot-agent;
          echo "DC logs "; docker logs dc;
          echo "Dummy logs"; docker logs dummy_destination;
          echo "Agent logs"; docker exec -i anodot-agent cat /var/log/agent/agent.log;
